name: dicolite
description: DICO Lite

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/libraryarchive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version:  0.1.10+1

environment:
  sdk: ">=2.12.0 <3.0.0"


  # flutter pub outdated

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  intl: ^0.17.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.6
  package_info: ^2.0.2
  overlay_support: ^1.2.1

  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  mobx_codegen: ^2.0.4

  json_serializable: ^6.1.3
  flutter_aes_ecb_pkcs5_fork: ^0.1.3
  rxdart: ^0.27.1
  flutter_svg: ^1.0.0
  convert: ^3.0.1

  decimal: ^1.3.0

  flutter_localizations:
    sdk: flutter

  qr_flutter: ^4.0.0
  device_info: ^2.0.2
  scan: ^1.0.0
  
  charts_flutter: 
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  update_app: ^0.1.7

  biometric_storage: ^4.0.1
  

  refresh_loadmore: ^2.0.4
  url_launcher: ^6.0.20
  file_picker: ^4.3.0
  sentry_flutter: ^6.1.2
  flutter_inappwebview: ^5.3.2
  cached_network_image: ^3.1.0

  extended_nested_scroll_view: ^5.0.0
  pull_to_refresh_notification: ^2.2.0
  dijkstra: ^0.0.2
  photo_view: ^0.13.0
  crypto: ^3.0.1
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.6

  flutter_test:
    sdk: flutter

dependency_overrides:
  # intl: '>=0.16.0'
  # path_drawing: '>=0.4.1'

# icons flutter_launcher_icons
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo-icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  
  assets:
    # js service
    - lib/polkadot_js_service/dist/main.js
    # images
    - assets/images/
    - assets/images/main/
    - assets/images/coins/
    - assets/images/dico/
    - assets/images/assets/
    - assets/images/gov/

  fonts:
    
    - family: SourceHanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansCN/SourceHanSansCN-Regular.ttf
        - asset: assets/fonts/SourceHanSansCN/SourceHanSansCN-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceHanSansCN/SourceHanSansCN-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceHanSansCN/SourceHanSansCN-Bold.ttf
          weight: 700
      
      


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

